### Create a new patient entity
POST http://localhost:2000/patients
Content-Type: application/json

{
  "name": "john Doe",
  "email": "test@gmail.com",
  "address": "mumbai maharashtra",
  "dateOfBirth": "2002-01-08",
  "registeredDate": ""
}

###